{% set name = "dash-bio" %}
{% set pkgname = "dash_bio" %}
{% set version = "0.7.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ pkgname }}-{{ version }}.tar.gz"
  sha256: 5436669e0aef280654a21f756b35cda03f58b10bfd8e6a19217f64966a941eb9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - dash >=1.6.1
    - pandas
    - plotly
    - python
    - scikit-learn >=0.20.1
    - scipy

test:
  imports:
    - dash_bio
    - dash_bio.component_factory

about:
  home: "http://github.com/plotly/dash-bio"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "dash_bio"
  doc_url: "https://dash.plot.ly/dash-bio"
  dev_url: "http://github.com/plotly/dash-bio"
